# Generated by Django 4.2.11 on 2024-04-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rylamain', '0002_rename_staff_users_available_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users_available',
            options={'verbose_name': 'USER', 'verbose_name_plural': 'USERS AVAILABLE'},
        ),
        migrations.AlterField(
            model_name='users_available',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
